### ISSUE TITLE
Unable to save at details tab (https://dogtag.chiditarod.org/teams/XXX/questions)

### ISSUE THREAD

**Issue by lodasi** [chiditarod/dogtag#12]
When attempting to save a valid form, the following error message appears:
translation missing: en.could_not_save_questions

I have tried to do this at least 20 times.

**Comment by ometa** [comment]
Thanks, what's your browser and operating system?

**Comment by lodasi** [comment]
Chrome 39.0.2171.99 (64-bit) on OS X Lion (10.7.5)
Most-recent Chrome on iOS 7 iPad 4

**Comment by lodasi** [comment]
The error message has evolved to:
"There was an issue saving your questions."

**Comment by lodasi** [comment]
Just attempted on a computer running Chrome on Windows 7. Received the same "There was an issue saving your questions." error message.

**Comment by lodasi** [comment]
I renamed the duplicate team mentioned in my other issue, and my registration issues were resolved.

**Comment by ometa** [comment]
Just added some code to disable the submit button after press.
