### ISSUE TITLE
Unable to delete duplicated team from dogPen

### ISSUE THREAD

**Issue by lodasi** [chiditarod/dogtag#13]
For some reason, DogTag created two teams in my dogPen with the same name and description. User is unable to delete the duplicated team.

**Comment by ometa** [comment]
Which do you want deleted?  This one? https://dogtag.chiditarod.org/teams/178

**Comment by lodasi** [comment]
Yes, please.

**Comment by ometa** [comment]
Sure, will take care of it for you by end of the weekend.  :smiling_imp:

**Comment by lodasi** [comment]
I'm starting to think that my registration issues are due to this
duplicated team. Please remedy this ASAP.

**Comment by lodasi** [comment]
I renamed the duplicate team and my registration issues were solved.

**Comment by ometa** [comment]
Done.
